### ISSUE TITLE
apiとの通信中のエラーハンドリング

### ISSUE THREAD

**Issue by yamad07** [tanimutomo/simple-api-server-go#3]
https://github.com/tanimutomo/simple-api-server-go/blob/e5a4d827edaa6d3e974503a2c7d503bb0b275e71/handler/article.go#L66
apiとの通信中にpanicすると挙動がおかしくなるので、apiとの通信中は基本的にpanicせずに、エラーを返してあげる。
エラーは、
```
{
  code: 400
  message: ""
}
```
みたいな感じの構造体を作って返すようにする。
ところどころエラーハンドリングしてるところがあるので、それをいろんなパターンで網羅する。

返すエラーの代表的な例としては、
1. pathのparamのidがおかしいとき
たとえば、`example.com/users/10/articles/10`
みたいな感じでアクセスしたとき、idが10のuserがないとき、あるいはidが10のarticleがないときは、404を返す。URLのパスのパラメータがおかしいときは、404を返す。
2. bodyがおかしいとき
たとえば、POSTの処理とかで、stringの値が欲しいのにintが飛んできたら、400を返す(Bad Request)。
3. 認証に失敗したとき
JWTのトークンがexpiredしたときや、トークンの値がおかしいときは、400を返す。
その上で、expiredしたときだけフロント(iOSやWeb)からrefresh_tokenを叩き直すようにしたいので、messageもexpiredのときとトークンの値がおかしいときでちゃんとわかりやすくする。

**Comment by tanimutomo** [comment]
確認なんだけど，status codeは，responseのbodyの中にも記述した方がいいんですか？

**Comment by yamad07** [comment]
あー、基本的にはbodyにいれなくて大丈夫かな
だから、bodyにはmessageだけ書くようにするか
(この辺は割と好みだったりするけど、情報の二重化という意味では、bodyにstatus code書かない方が良いかも)

**Comment by tanimutomo** [comment]
なるほどです，
一旦bodyには記述しない形式で書き直します！
