### ISSUE TITLE
requestとmodelが密結合になっている

### ISSUE THREAD

**Issue by yamad07** [tanimutomo/simple-api-server-go#4]
requestとmodelは密結合にしないと、requestの数だけgormのモデル作ったりしないといけないので、requestは純粋な構造体をhandlerのファイルとかに書いてしまった方が良い。
```
type LoginRequest struct {
  UserName 
  Password
}
```
みたいなを作って、Bindしたあと、handlerの中でUserモデルを明示的に初期化して、CreateUserのメソッドとかを読べば、ModelとRequestが疎結合になる
CreateUserみたいに、DBのロジックが抽象化された関数を作るっていうのはすごく良い！！！

**Comment by tanimutomo** [comment]
確かに，どうするんだろうと迷って，ああしてしまった．．なるほどです．
> CreateUserみたいに、DBのロジックが抽象化された関数を作るっていうのはすごく良い！！！

嬉しい！よかった！
