### ISSUE TITLE
APIが返す値を全てリソースにする

### ISSUE THREAD

**Issue by yamad07** [tanimutomo/simple-api-server-go#5]
APIに対して何かリクエストを投げたときに、帰ってくるレスポンスが必ずリソースになっていた方が、処理の結果がわかりやすい。
たとえば、Loginしたときに、Loginできた、っていうメッセージが帰ってくるんじゃなくて、ログインしたときのUserの情報が帰ってくるとか、TagをPOSTしたときに、そのTagの情報が帰ってくるみたいな感じ。

**Comment by tanimutomo** [comment]
これは，エラーになったかどうかにかかわらず，response bodyはrequstされたリソースにするということ？
つまり，request bodyの内容とか構造が正しくないエラーの時のとかに，そのエラーの趣旨をmessageか何かにつめて伝える必要はない？？
